add_custom_target(devicetree_target)

set_target_properties(devicetree_target PROPERTIES "DT_NODE|/" TRUE)
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/|compatible" "myvendor,miniboard;")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/|NUM" "0")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/|ADDR" "")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/|SIZE" "")
set_target_properties(devicetree_target PROPERTIES "DT_NODE|/i2c@40003000" TRUE)
set_target_properties(devicetree_target PROPERTIES "DT_NODELABEL|i2c0" "/i2c@40003000")
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/i2c@40003000|reg" "1073754112;4096;")
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/i2c@40003000|status" "okay")
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/i2c@40003000|compatible" "myvendor,i2c-controller;")
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/i2c@40003000|zephyr,deferred-init" "False")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/i2c@40003000|NUM" "1")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/i2c@40003000|ADDR" "0x40003000;")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/i2c@40003000|SIZE" "0x1000;")
set_target_properties(devicetree_target PROPERTIES "DT_NODE|/i2c@40003000/sensor@76" TRUE)
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/i2c@40003000/sensor@76|compatible" "myvendor,sensor;")
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/i2c@40003000/sensor@76|reg" "118;")
set_target_properties(devicetree_target PROPERTIES "DT_PROP|/i2c@40003000/sensor@76|status" "okay")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/i2c@40003000/sensor@76|NUM" "1")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/i2c@40003000/sensor@76|ADDR" "0x76;")
set_target_properties(devicetree_target PROPERTIES "DT_REG|/i2c@40003000/sensor@76|SIZE" "NONE;")
set_target_properties(devicetree_target PROPERTIES "DT_COMP|myvendor,miniboard" "/")
set_target_properties(devicetree_target PROPERTIES "DT_COMP|myvendor,i2c-controller" "/i2c@40003000")
set_target_properties(devicetree_target PROPERTIES "DT_COMP|myvendor,sensor" "/i2c@40003000/sensor@76")
